### ISSUE TITLE
Item duplication with cardboard boxes

### ISSUE THREAD

**Issue by dathide** [Luligabi1/CoxinhaUtilities#10]
Thanks for the great mod! I encountered a way to duplicate items. To reproduce:

- Install Coxinha Utilities and Extra Generators
- Place down a Withered Generator and insert a stack of Wither Stars
- Use a Cardboard Box on the Withered Generator
- A stack of Wither Stars will drop on the ground upon using the Cardboard Box
- When unpacking the Withered Generator, it will still have the original Wither Stars in it
- Now the player has 128 Wither Stars

**Comment by Luligabi1** [comment]
Fixed in dev branch, a public release will be out soon. Thanks for reporting!
