### ISSUE TITLE
Z fighting on glass of portable tank

### ISSUE THREAD

**Issue by TheWinABagel** [Luligabi1/CoxinhaUtilities#13]
![image](https://user-images.githubusercontent.com/17460735/185484330-a12376d8-6ea3-49a9-b325-fd2dc3e13741.png)

**Comment by Luligabi1** [comment]
Can you send your modlist? Couldn't reproduce.

**Comment by Gbergz** [comment]
Also have this issue, modlist in this modpack: [CurseForge](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-refabricated/files/3956446) scroll down.

My guess would be any of the performance enhancing mods, Sodium, Starlight or Iris etc.
![image](https://user-images.githubusercontent.com/26634554/187278703-12eeea77-405f-45d4-9a0c-23c3ac2fc634.png)

**Comment by TheWinABagel** [comment]
Sorry about not getting back to this sooner, my classes started and I got very busy very suddenly
Was using All of fabric 5 version 1.4.1, with Coxinha Utilities version 1.4.2
Will do some thorough testing

**Comment by TheWinABagel** [comment]
![image](https://user-images.githubusercontent.com/17460735/187532327-19baf45e-489c-43de-95f4-48e98d3432a5.png)
Getting this with only Coxinha Utilities, FAPI, Fabric Kotlin, and Kibe
Coxinha Utilities 1.4.2
FAPI 0.58.0
Fabric Language Kotlin 1.8.2
Kibe 1.9.9-BETA

**Comment by Luligabi1** [comment]
I've been stumped on how to fix this for a while, but I think it might have something to do with the graphic mode you're using. Are you on Fast, Fancy or Fabuluous? Does the z-fighting also happen when the tank is in your hand?

**Comment by Luligabi1** [comment]
Couldn't reproduce on fancy and fabuluous either.

**Comment by Gbergz** [comment]
Tried on Fast, Fancy & Fabulous, placed and in hand while in inventory, still has the issue. (z fight)

**Comment by Gbergz** [comment]
GPU is Nvidia (RTX 3080)
Intel CPU, (i7 8700k)
Java version 17.0.1

if any of this matters.

**Comment by Luligabi1** [comment]
It shouldn't matter, but It might. I have an AMD apu, so It might be an
issue only on Intel. I'll have some friends test if the can reproduce this
on AMD.

Em seg., 26 de set. de 2022 13:05, Gbergz ***@***.***>
escreveu:
