### ISSUE TITLE
Z fighting on Granny's Sink

### ISSUE THREAD

**Issue by Luligabi1** [Luligabi1/CoxinhaUtilities#14]
![image](https://user-images.githubusercontent.com/33578169/192288228-251b5958-ec4f-44f8-ad30-2c79873cfb6b.png)

**Comment by JTK222** [comment]
This is not z-fighting, but caused by your model having an UV of 0,0 0,0
Btw, you might want to use the optimize plugin in BB to optimize some of those models, they have many parts rendering, that are never visible.
