### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by Red6785** [Luligabi1/CoxinhaUtilities#18]
[crash-2022-12-04_14.52.24-client.txt](https://github.com/Luligabi1/CoxinhaUtilities/files/10149437/crash-2022-12-04_14.52.24-client.txt)

**Comment by Luligabi1** [comment]
I'll need more details.

- When did It crash? Does it continue to happen everytime you attempt to open the world?
- your full modlist

**Comment by Red6785** [comment]
It crashed while I searched "Mer" In the creative item list. The crash log says its trying to render granny's sink. it doesn't happen until I search mer again. as for the modlist, one sec

**Comment by Red6785** [comment]
Im pretty sure the modlist is in the crashlog, is it not? It's there for me, just formatted strangely.

**Comment by Red6785** [comment]
[modlist.txt](https://github.com/Luligabi1/CoxinhaUtilities/files/10149462/modlist.txt)

**Comment by Red6785** [comment]
sorry about that, used the curseforge export modpack feature there so it gave me a file

**Comment by Red6785** [comment]
I also crashed again while i was doing something else, this time when I filled up a fluid tank.
[crash-2022-12-04_15.01.44-client.txt](https://github.com/Luligabi1/CoxinhaUtilities/files/10149466/crash-2022-12-04_15.01.44-client.txt)

**Comment by Red6785** [comment]
Read the crashlog a little myself, saw the fabric rendering api error, added Indium, now it's fixed. Sorry for wasting your time!
