### ISSUE TITLE
[Feature Request] Allow non-block entities to be cardboard boxed

### ISSUE THREAD

**Issue by BernardoGrigiastro** [Luligabi1/CoxinhaUtilities#21]
Allow AE2 budding blocks to be cardboard boxed (just like the og :) )

Thx

**Comment by Luligabi1** [comment]
Will require a bit of rewriting, so I'm putting it off until at least 1.20 comes around.

**Comment by Luligabi1** [comment]
Now a feature on `1.4.8+1.19.4` onwards

**Comment by BernardoGrigiastro** [comment]
Thank you!!
