### ISSUE TITLE
[Bug] Sometimes empty cardboard boxes cant stack

### ISSUE THREAD

**Issue by milkev** [Luligabi1/CoxinhaUtilities#27]
**Description**
After using a cardboard box, it cant be stacked with an unused cardboard box, or one that was placed normally (not boxing anything up) and broken.
from the /data report, it seems to be because the boxes that were shift right clicked off of blocks retain a blank nbt tag, which is not present in the unused cardboard box.
![image](https://github.com/Luligabi1/CoxinhaUtilities/assets/22010128/b2ccbd65-3c4d-456b-bd4c-34527a347f09)

**Versions**
Coxinha 1.4.10 for 1.20.1
Fabric 0.14.22 api 0.87.0
*Various others, can provide if you want

**Comment by Luligabi1** [comment]
Fixed on `dev/1.20` branch, will be on the next public release 👍🏼
