### ISSUE TITLE
Drying rack has an inventory that ends up deleting excess items.

### ISSUE THREAD

**Issue by DplusAlphaR4** [Luligabi1/CoxinhaUtilities#8]
The Drying rack has an inventory exceeding 1 item, which cannot be accessed manually, but can be pulled from. This means you can pipe items into it with hoppers/pipes and when the block updates, lets say from drying cooked meat into leather, 1 leather will be produced; but if 2 stacks of cooked bacon were in the rack, then they will end up being deleted.

**Comment by Luligabi1** [comment]
Drying racks aren't supposed to be automatable (hence no hopper support) if a pipe checks directly for the inventory, that's the pipe's mod issue, not Coxinha Utilities.
